// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo0O20er5CTJMOcaoEUSgvoHogy6l-n00',
    appId: '1:567431096611:web:eb405b7c1b025b53954496',
    messagingSenderId: '567431096611',
    projectId: 'aggiebites',
    authDomain: 'aggiebites.firebaseapp.com',
    storageBucket: 'aggiebites.appspot.com',
    measurementId: 'G-EG8YP161FR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDds_hX7vlWEcS-fXmg8-3h9gQbANogiEg',
    appId: '1:567431096611:android:0f34fbf3d77b349d954496',
    messagingSenderId: '567431096611',
    projectId: 'aggiebites',
    storageBucket: 'aggiebites.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCoq8E7gHLce8FCWbgLcP1st77gTwe8F0',
    appId: '1:567431096611:ios:0d4343ea76ac722a954496',
    messagingSenderId: '567431096611',
    projectId: 'aggiebites',
    storageBucket: 'aggiebites.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCoq8E7gHLce8FCWbgLcP1st77gTwe8F0',
    appId: '1:567431096611:ios:0d4343ea76ac722a954496',
    messagingSenderId: '567431096611',
    projectId: 'aggiebites',
    storageBucket: 'aggiebites.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDo0O20er5CTJMOcaoEUSgvoHogy6l-n00',
    appId: '1:567431096611:web:c576c7658cf5c6a3954496',
    messagingSenderId: '567431096611',
    projectId: 'aggiebites',
    authDomain: 'aggiebites.firebaseapp.com',
    storageBucket: 'aggiebites.appspot.com',
    measurementId: 'G-23LM22NWY6',
  );

}